DROP TABLE IF EXISTS mall_inventory;

CREATE TABLE mall_inventory
(
	id BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
    price DECIMAL(11,2) NULL DEFAULT NULL COMMENT '价格',
    name VARCHAR (255) NULL DEFAULT NULL COMMENT '名称',
    create_time DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME NULL DEFAULT NULL COMMENT '更新时间',
    stock INT(11) NULL DEFAULT NULL COMMENT '库存',
	PRIMARY KEY (id)
);